### ISSUE TITLE
#0 Set up project 

### ISSUE THREAD

**Issue by AlexandraGF** [bpourian/makersbnb#1]
- Ruby version 2.4.1

- Sinatra

- RSpec/Capybara

- Database : PostgreSQL

**Comment by samuelmaker** [comment]
🕵🏽👍

**Comment by bpourian** [comment]
I set up the  initial gem files. This was agreed with the mob. I hold the master copy in my .git
🐐

**Comment by reenz** [comment]
👍

**Comment by AlexandraGF** [comment]
🐹
