### ISSUE TITLE
Create: (list space) --> button 

### ISSUE THREAD

**Issue by bpourian** [bpourian/makersbnb#5]
```
As a User
So I can have someone hire a space
I want to list a space
```
Please add a feature so that a user can select button list spaces on (/spaces) page.
similar to the second image on the left column on this [link](https://github.com/makersacademy/course/blob/master/makersbnb/makers_bnb_images/MakersBnB_mockups.pdf)

**Comment by AlexandraGF** [comment]
Added a form to fill in description of the page and then added a button (List my Space) so the user is sent back to the spaces page with the new space created that is displayed on the spaces page.
